$publicFunctions = Get-ChildItem -Path (Join-Path $PSScriptRoot 'Public') -Filter '*.ps1' -File

foreach ($function in $publicFunctions) {
    . $function.FullName
}

Export-ModuleMember -Function @(
    'Compare-SchunkIncidentBundle'
    'Get-SchunkAccountLockoutTrace'
    'Get-SchunkADReplicationHealth'
    'Get-SchunkBitLockerInventory'
    'Get-SchunkCertificateInventory'
    'Get-SchunkClusterHealth'
    'Get-SchunkDhcpDnsConsistency'
    'Get-SchunkDhcpScopeHealth'
    'Get-SchunkDfsNamespaceHealth'
    'Get-SchunkDiskPressure'
    'Get-SchunkDnsServerHealth'
    'Get-SchunkDomainTrustStatus'
    'Get-SchunkEndpointTriage'
    'Get-SchunkEventTriage'
    'Get-SchunkFirewallAudit'
    'Get-SchunkFleetHealth'
    'Get-SchunkGpoChangeAudit'
    'Get-SchunkHyperVHealth'
    'Get-SchunkIisHealth'
    'Get-SchunkIisLogSummary'
    'Get-SchunkInstalledSoftware'
    'Get-SchunkKerberosSpnAudit'
    'Get-SchunkListeningPort'
    'Get-SchunkLocalAdministrator'
    'Get-SchunkLogonFailure'
    'Get-SchunkPendingReboot'
    'Get-SchunkPrivilegedGroupAudit'
    'Get-SchunkRdpHealth'
    'Get-SchunkScheduledTaskAudit'
    'Get-SchunkSmbPermissionAudit'
    'Get-SchunkServerHealth'
    'Get-SchunkServiceFailure'
    'Get-SchunkSqlServerHealth'
    'Get-SchunkVSphereInventory'
    'Get-SchunkWindowsUpdateHealth'
    'Get-SchunkWindowsBackupHealth'
    'Get-SchunkWindowsUpdateHistory'
    'Invoke-SchunkServerAudit'
    'New-SchunkIncidentBundle'
    'Test-SchunkCertificateChain'
    'Test-SchunkDnsClient'
    'Test-SchunkGpoApplication'
    'Test-SchunkNetworkPath'
    'Test-SchunkTlsEndpoint'
)
